/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
    profiles: ProfileAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    profiles: Profile;
    'profile-connections': ProfileConnection;
    'profile-groups': ProfileGroup;
    chats: Chat;
    'connection-requests': ConnectionRequest;
    notifications: Notification;
    jobs: Job;
    'job-templates': JobTemplate;
    'job-applications': JobApplication;
    'job-categories': JobCategory;
    'clinical-areas': ClinicalArea;
    'job-modalities': JobModality;
    places: Place;
    cities: City;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    profiles: ProfilesSelect<false> | ProfilesSelect<true>;
    'profile-connections': ProfileConnectionsSelect<false> | ProfileConnectionsSelect<true>;
    'profile-groups': ProfileGroupsSelect<false> | ProfileGroupsSelect<true>;
    chats: ChatsSelect<false> | ChatsSelect<true>;
    'connection-requests': ConnectionRequestsSelect<false> | ConnectionRequestsSelect<true>;
    notifications: NotificationsSelect<false> | NotificationsSelect<true>;
    jobs: JobsSelect<false> | JobsSelect<true>;
    'job-templates': JobTemplatesSelect<false> | JobTemplatesSelect<true>;
    'job-applications': JobApplicationsSelect<false> | JobApplicationsSelect<true>;
    'job-categories': JobCategoriesSelect<false> | JobCategoriesSelect<true>;
    'clinical-areas': ClinicalAreasSelect<false> | ClinicalAreasSelect<true>;
    'job-modalities': JobModalitiesSelect<false> | JobModalitiesSelect<true>;
    places: PlacesSelect<false> | PlacesSelect<true>;
    cities: CitiesSelect<false> | CitiesSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  globals: {};
  globalsSelect: {};
  locale: null;
  user:
    | (User & {
        collection: 'users';
      })
    | (Profile & {
        collection: 'profiles';
      });
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
export interface ProfileAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  type: 'PUBLIC' | 'USER';
  owner?:
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'profiles';
        value: string | Profile;
      } | null);
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "profiles".
 */
export interface Profile {
  id: string;
  name: string;
  profilePicture?: (string | null) | Media;
  /**
   * Número de WhatsApp para contato
   */
  whatsappNumber?: string | null;
  /**
   * Configurações para o processo de exclusão de conta (LGPD)
   */
  accountDeletion?: {
    requested?: boolean | null;
    /**
     * Data em que o usuário solicitou a exclusão
     */
    requestDate?: string | null;
    /**
     * Data em que a exclusão será efetivada após o período de carência
     */
    scheduledDate?: string | null;
    reason?: string | null;
    /**
     * Período em dias antes da exclusão ser efetivada
     */
    gracePeriodDays?: number | null;
    cancelled?: boolean | null;
    cancelledDate?: string | null;
    completed?: boolean | null;
  };
  /**
   * Campo legado, use o grupo "Exclusão de Conta"
   */
  scheduledRemovalDate?: string | null;
  notificationTokens?:
    | {
        value?: string | null;
        label?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Campo legado, use o grupo "Exclusão de Conta"
   */
  removedAccount?: boolean | null;
  /**
   * Filtros para o perfil
   */
  filters?: string | null;
  register: {
    type: 'CRM';
    number: number;
    uf:
      | 'AC'
      | 'AL'
      | 'AP'
      | 'AM'
      | 'BA'
      | 'CE'
      | 'DF'
      | 'ES'
      | 'GO'
      | 'MA'
      | 'MT'
      | 'MS'
      | 'MG'
      | 'PA'
      | 'PB'
      | 'PR'
      | 'PE'
      | 'PI'
      | 'RJ'
      | 'RN'
      | 'RS'
      | 'RO'
      | 'RR'
      | 'SC'
      | 'SP'
      | 'SE'
      | 'TO';
    verified?: boolean | null;
  };
  cpf?: string | null;
  phoneNumber?: string | null;
  about?: string | null;
  cities?: (string | City)[] | null;
  states?:
    | (
        | 'AC'
        | 'AL'
        | 'AP'
        | 'AM'
        | 'BA'
        | 'CE'
        | 'DF'
        | 'ES'
        | 'GO'
        | 'MA'
        | 'MT'
        | 'MS'
        | 'MG'
        | 'PA'
        | 'PB'
        | 'PR'
        | 'PE'
        | 'PI'
        | 'RJ'
        | 'RN'
        | 'RS'
        | 'RO'
        | 'RR'
        | 'SC'
        | 'SP'
        | 'SE'
        | 'TO'
      )[]
    | null;
  places?: (string | Place)[] | null;
  clinicalAreas?: (string | ClinicalArea)[] | null;
  graduationYear?: number | null;
  allRequiredInfoFilled?: boolean | null;
  moreRegisters?:
    | {
        description?: string | null;
        type: 'RQE';
        number: number;
        uf:
          | 'AC'
          | 'AL'
          | 'AP'
          | 'AM'
          | 'BA'
          | 'CE'
          | 'DF'
          | 'ES'
          | 'GO'
          | 'MA'
          | 'MT'
          | 'MS'
          | 'MG'
          | 'PA'
          | 'PB'
          | 'PR'
          | 'PE'
          | 'PI'
          | 'RJ'
          | 'RN'
          | 'RS'
          | 'RO'
          | 'RR'
          | 'SC'
          | 'SP'
          | 'SE'
          | 'TO';
        verified?: boolean | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  _verified?: boolean | null;
  _verificationToken?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cities".
 */
export interface City {
  id: string;
  label: string;
  name: string;
  uf: string;
  keys: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "places".
 */
export interface Place {
  id: string;
  name: string;
  city: string | City;
  formattedAddress?: string | null;
  postcode?: number | null;
  /**
   * @minItems 2
   * @maxItems 2
   */
  coordinates?: [number, number] | null;
  rating?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "clinical-areas".
 */
export interface ClinicalArea {
  id: string;
  name?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "profile-connections".
 */
export interface ProfileConnection {
  id: string;
  /**
   * Identificador único gerado automaticamente
   */
  uid: string;
  from: string | Profile;
  relationship: string | Profile;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "profile-groups".
 */
export interface ProfileGroup {
  id: string;
  name: string;
  owner: string | Profile;
  matrixRoomId?: string | null;
  description?: string | null;
  picture?: (string | null) | Media;
  managers?: (string | Profile)[] | null;
  members?: (string | Profile)[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "chats".
 */
export interface Chat {
  id: string;
  participants: (string | Profile)[];
  /**
   * Identificador único do chat no Matrix
   */
  matrixChatId: string;
  createdAt: string;
  updatedAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "connection-requests".
 */
export interface ConnectionRequest {
  id: string;
  from: string | Profile;
  to: string | Profile;
  status: 'PENDING' | 'ACCEPTED' | 'REJECTED';
  type: 'DIRECT' | 'GROUP_BASED';
  message?: string | null;
  relatedGroup?: (string | null) | ProfileGroup;
  respondedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notifications".
 */
export interface Notification {
  id: string;
  event: 'received:job-application';
  to: string | Profile;
  title: string;
  body: string;
  read?: boolean | null;
  data?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  iosThreadId?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "jobs".
 */
export interface Job {
  id: string;
  from?: (string | null) | Profile;
  to?: (string | null) | Profile;
  modality?: (string | null) | JobModality;
  clinicalArea?: (string | null) | ClinicalArea;
  state?:
    | (
        | 'AC'
        | 'AL'
        | 'AP'
        | 'AM'
        | 'BA'
        | 'CE'
        | 'DF'
        | 'ES'
        | 'GO'
        | 'MA'
        | 'MT'
        | 'MS'
        | 'MG'
        | 'PA'
        | 'PB'
        | 'PR'
        | 'PE'
        | 'PI'
        | 'RJ'
        | 'RN'
        | 'RS'
        | 'RO'
        | 'RR'
        | 'SC'
        | 'SP'
        | 'SE'
        | 'TO'
      )
    | null;
  city?: (string | null) | City;
  place?: (string | null) | Place;
  startDateTime?: string | null;
  durationInHours?: number | null;
  endDateTime?: string | null;
  applyChagesForAllAdditionalDates?: boolean | null;
  parentRef?: string | null;
  additionalDates?:
    | {
        date?: string | null;
        paidAt?: string | null;
        receivedAt?: string | null;
        id?: string | null;
      }[]
    | null;
  paymentMethod?: ('AV' | 'NR' | 'AC') | null;
  singlePaymentForMutipleDates?: boolean | null;
  description?: string | null;
  priceInCents?: number | null;
  isVerified?: boolean | null;
  restrictedToGuests?: (string | Profile)[] | null;
  interested?: (string | Profile)[] | null;
  restrictedToGroups?: (string | ProfileGroup)[] | null;
  previewImage?: (string | null) | Media;
  hasShared?: boolean | null;
  visibility?: ('PUBLIC' | 'UNLISTED' | 'RESTRICTED_TO_GUESTS' | 'RESTRICTED_TO_GROUPS' | 'PRIVATE') | null;
  paidAt?: string | null;
  receivedAt?: string | null;
  cancelledAt?: string | null;
  transferredAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "job-modalities".
 */
export interface JobModality {
  id: string;
  name?: string | null;
  clinicalAreas?: (string | ClinicalArea)[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "job-templates".
 */
export interface JobTemplate {
  id: string;
  from?: (string | null) | Profile;
  modality?: (string | null) | JobModality;
  clinicalArea?: (string | null) | ClinicalArea;
  state?:
    | (
        | 'AC'
        | 'AL'
        | 'AP'
        | 'AM'
        | 'BA'
        | 'CE'
        | 'DF'
        | 'ES'
        | 'GO'
        | 'MA'
        | 'MT'
        | 'MS'
        | 'MG'
        | 'PA'
        | 'PB'
        | 'PR'
        | 'PE'
        | 'PI'
        | 'RJ'
        | 'RN'
        | 'RS'
        | 'RO'
        | 'RR'
        | 'SC'
        | 'SP'
        | 'SE'
        | 'TO'
      )
    | null;
  city?: (string | null) | City;
  place?: (string | null) | Place;
  startTime?: string | null;
  durationInHours?: number | null;
  paymentMethod?: ('AV' | 'NR' | 'AC') | null;
  singlePaymentForMutipleDates?: boolean | null;
  description?: string | null;
  priceInCents?: number | null;
  restrictedToGuests?: (string | Profile)[] | null;
  restrictedToGroups?: (string | ProfileGroup)[] | null;
  visibility?: ('PUBLIC' | 'UNLISTED' | 'RESTRICTED_TO_GUESTS' | 'RESTRICTED_TO_GROUPS' | 'PRIVATE') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "job-applications".
 */
export interface JobApplication {
  id: string;
  job?: (string | null) | Job;
  publisher: string | Profile;
  applicant: string | Profile;
  status: 'PENDING' | 'ACCEPTED' | 'REJECTED';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "job-categories".
 */
export interface JobCategory {
  id: string;
  name?: string | null;
  description?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'profiles';
        value: string | Profile;
      } | null)
    | ({
        relationTo: 'profile-connections';
        value: string | ProfileConnection;
      } | null)
    | ({
        relationTo: 'profile-groups';
        value: string | ProfileGroup;
      } | null)
    | ({
        relationTo: 'chats';
        value: string | Chat;
      } | null)
    | ({
        relationTo: 'connection-requests';
        value: string | ConnectionRequest;
      } | null)
    | ({
        relationTo: 'notifications';
        value: string | Notification;
      } | null)
    | ({
        relationTo: 'jobs';
        value: string | Job;
      } | null)
    | ({
        relationTo: 'job-templates';
        value: string | JobTemplate;
      } | null)
    | ({
        relationTo: 'job-applications';
        value: string | JobApplication;
      } | null)
    | ({
        relationTo: 'job-categories';
        value: string | JobCategory;
      } | null)
    | ({
        relationTo: 'clinical-areas';
        value: string | ClinicalArea;
      } | null)
    | ({
        relationTo: 'job-modalities';
        value: string | JobModality;
      } | null)
    | ({
        relationTo: 'places';
        value: string | Place;
      } | null)
    | ({
        relationTo: 'cities';
        value: string | City;
      } | null);
  globalSlug?: string | null;
  user:
    | {
        relationTo: 'users';
        value: string | User;
      }
    | {
        relationTo: 'profiles';
        value: string | Profile;
      };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user:
    | {
        relationTo: 'users';
        value: string | User;
      }
    | {
        relationTo: 'profiles';
        value: string | Profile;
      };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  type?: T;
  owner?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "profiles_select".
 */
export interface ProfilesSelect<T extends boolean = true> {
  name?: T;
  profilePicture?: T;
  whatsappNumber?: T;
  accountDeletion?:
    | T
    | {
        requested?: T;
        requestDate?: T;
        scheduledDate?: T;
        reason?: T;
        gracePeriodDays?: T;
        cancelled?: T;
        cancelledDate?: T;
        completed?: T;
      };
  scheduledRemovalDate?: T;
  notificationTokens?:
    | T
    | {
        value?: T;
        label?: T;
        id?: T;
      };
  removedAccount?: T;
  filters?: T;
  register?:
    | T
    | {
        type?: T;
        number?: T;
        uf?: T;
        verified?: T;
      };
  cpf?: T;
  phoneNumber?: T;
  about?: T;
  cities?: T;
  states?: T;
  places?: T;
  clinicalAreas?: T;
  graduationYear?: T;
  allRequiredInfoFilled?: T;
  moreRegisters?:
    | T
    | {
        description?: T;
        type?: T;
        number?: T;
        uf?: T;
        verified?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  _verified?: T;
  _verificationToken?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "profile-connections_select".
 */
export interface ProfileConnectionsSelect<T extends boolean = true> {
  uid?: T;
  from?: T;
  relationship?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "profile-groups_select".
 */
export interface ProfileGroupsSelect<T extends boolean = true> {
  name?: T;
  owner?: T;
  matrixRoomId?: T;
  description?: T;
  picture?: T;
  managers?: T;
  members?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "chats_select".
 */
export interface ChatsSelect<T extends boolean = true> {
  participants?: T;
  matrixChatId?: T;
  createdAt?: T;
  updatedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "connection-requests_select".
 */
export interface ConnectionRequestsSelect<T extends boolean = true> {
  from?: T;
  to?: T;
  status?: T;
  type?: T;
  message?: T;
  relatedGroup?: T;
  respondedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notifications_select".
 */
export interface NotificationsSelect<T extends boolean = true> {
  event?: T;
  to?: T;
  title?: T;
  body?: T;
  read?: T;
  data?: T;
  iosThreadId?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "jobs_select".
 */
export interface JobsSelect<T extends boolean = true> {
  from?: T;
  to?: T;
  modality?: T;
  clinicalArea?: T;
  state?: T;
  city?: T;
  place?: T;
  startDateTime?: T;
  durationInHours?: T;
  endDateTime?: T;
  applyChagesForAllAdditionalDates?: T;
  parentRef?: T;
  additionalDates?:
    | T
    | {
        date?: T;
        paidAt?: T;
        receivedAt?: T;
        id?: T;
      };
  paymentMethod?: T;
  singlePaymentForMutipleDates?: T;
  description?: T;
  priceInCents?: T;
  isVerified?: T;
  restrictedToGuests?: T;
  interested?: T;
  restrictedToGroups?: T;
  previewImage?: T;
  hasShared?: T;
  visibility?: T;
  paidAt?: T;
  receivedAt?: T;
  cancelledAt?: T;
  transferredAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "job-templates_select".
 */
export interface JobTemplatesSelect<T extends boolean = true> {
  from?: T;
  modality?: T;
  clinicalArea?: T;
  state?: T;
  city?: T;
  place?: T;
  startTime?: T;
  durationInHours?: T;
  paymentMethod?: T;
  singlePaymentForMutipleDates?: T;
  description?: T;
  priceInCents?: T;
  restrictedToGuests?: T;
  restrictedToGroups?: T;
  visibility?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "job-applications_select".
 */
export interface JobApplicationsSelect<T extends boolean = true> {
  job?: T;
  publisher?: T;
  applicant?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "job-categories_select".
 */
export interface JobCategoriesSelect<T extends boolean = true> {
  name?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "clinical-areas_select".
 */
export interface ClinicalAreasSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "job-modalities_select".
 */
export interface JobModalitiesSelect<T extends boolean = true> {
  name?: T;
  clinicalAreas?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "places_select".
 */
export interface PlacesSelect<T extends boolean = true> {
  id?: T;
  name?: T;
  city?: T;
  formattedAddress?: T;
  postcode?: T;
  coordinates?: T;
  rating?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cities_select".
 */
export interface CitiesSelect<T extends boolean = true> {
  label?: T;
  name?: T;
  uf?: T;
  keys?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}